// Code generated by protoc-gen-go. DO NOT EDIT.
// source: complex/complex.proto

package complexpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ComplexMessage struct {
	Msg                  *DummyMessage   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Dummies              []*DummyMessage `protobuf:"bytes,2,rep,name=dummies,proto3" json:"dummies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ComplexMessage) Reset()         { *m = ComplexMessage{} }
func (m *ComplexMessage) String() string { return proto.CompactTextString(m) }
func (*ComplexMessage) ProtoMessage()    {}
func (*ComplexMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_467978440e6d1735, []int{0}
}

func (m *ComplexMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexMessage.Unmarshal(m, b)
}
func (m *ComplexMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexMessage.Marshal(b, m, deterministic)
}
func (m *ComplexMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexMessage.Merge(m, src)
}
func (m *ComplexMessage) XXX_Size() int {
	return xxx_messageInfo_ComplexMessage.Size(m)
}
func (m *ComplexMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexMessage proto.InternalMessageInfo

func (m *ComplexMessage) GetMsg() *DummyMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ComplexMessage) GetDummies() []*DummyMessage {
	if m != nil {
		return m.Dummies
	}
	return nil
}

type DummyMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyMessage) Reset()         { *m = DummyMessage{} }
func (m *DummyMessage) String() string { return proto.CompactTextString(m) }
func (*DummyMessage) ProtoMessage()    {}
func (*DummyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_467978440e6d1735, []int{1}
}

func (m *DummyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyMessage.Unmarshal(m, b)
}
func (m *DummyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyMessage.Marshal(b, m, deterministic)
}
func (m *DummyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyMessage.Merge(m, src)
}
func (m *DummyMessage) XXX_Size() int {
	return xxx_messageInfo_DummyMessage.Size(m)
}
func (m *DummyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DummyMessage proto.InternalMessageInfo

func (m *DummyMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DummyMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ComplexMessage)(nil), "example.complex.ComplexMessage")
	proto.RegisterType((*DummyMessage)(nil), "example.complex.DummyMessage")
}

func init() { proto.RegisterFile("complex/complex.proto", fileDescriptor_467978440e6d1735) }

var fileDescriptor_467978440e6d1735 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0xcf, 0x2d,
	0xc8, 0x49, 0xad, 0xd0, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xfc, 0xa9, 0x15,
	0x89, 0x20, 0xbe, 0x1e, 0x54, 0x58, 0xa9, 0x8a, 0x8b, 0xcf, 0x19, 0xc2, 0xf4, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x15, 0xd2, 0xe7, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x36, 0x92, 0xd5, 0x43, 0xd3, 0xa0, 0xe7, 0x52, 0x9a, 0x9b, 0x5b, 0x09, 0x55, 0x1b, 0x04, 0x52,
	0x29, 0x64, 0xce, 0xc5, 0x9e, 0x52, 0x9a, 0x9b, 0x9b, 0x99, 0x5a, 0x2c, 0xc1, 0xa4, 0xc0, 0x4c,
	0x58, 0x13, 0x4c, 0xb5, 0x92, 0x11, 0x17, 0x0f, 0xb2, 0x84, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x0a,
	0xd8, 0x62, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0xdb, 0x89, 0x3b, 0x8a, 0x13, 0x6a, 0x68, 0x41, 0x52,
	0x12, 0x1b, 0xd8, 0x53, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x57, 0x6f, 0xb3, 0xed,
	0x00, 0x00, 0x00,
}
