// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 4-enum.proto

public final class 4Enum {
  private 4Enum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the age as of the person's creation
     * </pre>
     *
     * <code>int32 age = 1;</code>
     */
    int getAge();

    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     */
    java.lang.String getFirstName();
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <pre>
     * the last name as documented in the signup form
     * </pre>
     *
     * <code>string last_name = 3;</code>
     */
    java.lang.String getLastName();
    /**
     * <pre>
     * the last name as documented in the signup form
     * </pre>
     *
     * <code>string last_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <pre>
     * small_picture represents a small .jpg file
     * </pre>
     *
     * <code>bytes small_picture = 4;</code>
     */
    com.google.protobuf.ByteString getSmallPicture();

    /**
     * <code>bool is_profile_verified = 5;</code>
     */
    boolean getIsProfileVerified();

    /**
     * <pre>
     * height of the person in cms
     * </pre>
     *
     * <code>float height = 6;</code>
     */
    float getHeight();

    /**
     * <pre>
     * a list of phone numbers tha is optional to provide in signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    java.util.List<java.lang.String>
        getPhonesList();
    /**
     * <pre>
     * a list of phone numbers tha is optional to provide in signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    int getPhonesCount();
    /**
     * <pre>
     * a list of phone numbers tha is optional to provide in signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    java.lang.String getPhones(int index);
    /**
     * <pre>
     * a list of phone numbers tha is optional to provide in signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    com.google.protobuf.ByteString
        getPhonesBytes(int index);

    /**
     * <code>.Person.EyeColor eyeColor = 8;</code>
     */
    int getEyeColorValue();
    /**
     * <code>.Person.EyeColor eyeColor = 8;</code>
     */
    4Enum.Person.EyeColor getEyeColor();
  }
  /**
   * <pre>
   * Person is used to identify users
   * across our systems 
   * </pre>
   *
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      firstName_ = "";
      lastName_ = "";
      smallPicture_ = com.google.protobuf.ByteString.EMPTY;
      phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      eyeColor_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              age_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {

              smallPicture_ = input.readBytes();
              break;
            }
            case 40: {

              isProfileVerified_ = input.readBool();
              break;
            }
            case 53: {

              height_ = input.readFloat();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                phones_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              phones_.add(s);
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              eyeColor_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) != 0)) {
          phones_ = phones_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return 4Enum.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return 4Enum.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              4Enum.Person.class, 4Enum.Person.Builder.class);
    }

    /**
     * Protobuf enum {@code Person.EyeColor}
     */
    public enum EyeColor
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKKOW_COLOR = 0;</code>
       */
      UNKKOW_COLOR(0),
      /**
       * <code>BLUE = 1;</code>
       */
      BLUE(1),
      /**
       * <code>BROWN = 2;</code>
       */
      BROWN(2),
      /**
       * <code>GREEN = 3;</code>
       */
      GREEN(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKKOW_COLOR = 0;</code>
       */
      public static final int UNKKOW_COLOR_VALUE = 0;
      /**
       * <code>BLUE = 1;</code>
       */
      public static final int BLUE_VALUE = 1;
      /**
       * <code>BROWN = 2;</code>
       */
      public static final int BROWN_VALUE = 2;
      /**
       * <code>GREEN = 3;</code>
       */
      public static final int GREEN_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EyeColor valueOf(int value) {
        return forNumber(value);
      }

      public static EyeColor forNumber(int value) {
        switch (value) {
          case 0: return UNKKOW_COLOR;
          case 1: return BLUE;
          case 2: return BROWN;
          case 3: return GREEN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EyeColor>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EyeColor> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EyeColor>() {
              public EyeColor findValueByNumber(int number) {
                return EyeColor.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return 4Enum.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final EyeColor[] VALUES = values();

      public static EyeColor valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EyeColor(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.EyeColor)
    }

    private int bitField0_;
    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <pre>
     * the age as of the person's creation
     * </pre>
     *
     * <code>int32 age = 1;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <pre>
     * the last name as documented in the signup form
     * </pre>
     *
     * <code>string last_name = 3;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the last name as documented in the signup form
     * </pre>
     *
     * <code>string last_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SMALL_PICTURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString smallPicture_;
    /**
     * <pre>
     * small_picture represents a small .jpg file
     * </pre>
     *
     * <code>bytes small_picture = 4;</code>
     */
    public com.google.protobuf.ByteString getSmallPicture() {
      return smallPicture_;
    }

    public static final int IS_PROFILE_VERIFIED_FIELD_NUMBER = 5;
    private boolean isProfileVerified_;
    /**
     * <code>bool is_profile_verified = 5;</code>
     */
    public boolean getIsProfileVerified() {
      return isProfileVerified_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private float height_;
    /**
     * <pre>
     * height of the person in cms
     * </pre>
     *
     * <code>float height = 6;</code>
     */
    public float getHeight() {
      return height_;
    }

    public static final int PHONES_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList phones_;
    /**
     * <pre>
     * a list of phone numbers tha is optional to provide in signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhonesList() {
      return phones_;
    }
    /**
     * <pre>
     * a list of phone numbers tha is optional to provide in signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <pre>
     * a list of phone numbers tha is optional to provide in signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    public java.lang.String getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <pre>
     * a list of phone numbers tha is optional to provide in signup
     * </pre>
     *
     * <code>repeated string phones = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPhonesBytes(int index) {
      return phones_.getByteString(index);
    }

    public static final int EYECOLOR_FIELD_NUMBER = 8;
    private int eyeColor_;
    /**
     * <code>.Person.EyeColor eyeColor = 8;</code>
     */
    public int getEyeColorValue() {
      return eyeColor_;
    }
    /**
     * <code>.Person.EyeColor eyeColor = 8;</code>
     */
    public 4Enum.Person.EyeColor getEyeColor() {
      @SuppressWarnings("deprecation")
      4Enum.Person.EyeColor result = 4Enum.Person.EyeColor.valueOf(eyeColor_);
      return result == null ? 4Enum.Person.EyeColor.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (age_ != 0) {
        output.writeInt32(1, age_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!smallPicture_.isEmpty()) {
        output.writeBytes(4, smallPicture_);
      }
      if (isProfileVerified_ != false) {
        output.writeBool(5, isProfileVerified_);
      }
      if (height_ != 0F) {
        output.writeFloat(6, height_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phones_.getRaw(i));
      }
      if (eyeColor_ != 4Enum.Person.EyeColor.UNKKOW_COLOR.getNumber()) {
        output.writeEnum(8, eyeColor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!smallPicture_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, smallPicture_);
      }
      if (isProfileVerified_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isProfileVerified_);
      }
      if (height_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, height_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phones_.size(); i++) {
          dataSize += computeStringSizeNoTag(phones_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhonesList().size();
      }
      if (eyeColor_ != 4Enum.Person.EyeColor.UNKKOW_COLOR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, eyeColor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof 4Enum.Person)) {
        return super.equals(obj);
      }
      4Enum.Person other = (4Enum.Person) obj;

      if (getAge()
          != other.getAge()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getSmallPicture()
          .equals(other.getSmallPicture())) return false;
      if (getIsProfileVerified()
          != other.getIsProfileVerified()) return false;
      if (java.lang.Float.floatToIntBits(getHeight())
          != java.lang.Float.floatToIntBits(
              other.getHeight())) return false;
      if (!getPhonesList()
          .equals(other.getPhonesList())) return false;
      if (eyeColor_ != other.eyeColor_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + SMALL_PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getSmallPicture().hashCode();
      hash = (37 * hash) + IS_PROFILE_VERIFIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsProfileVerified());
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeight());
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      hash = (37 * hash) + EYECOLOR_FIELD_NUMBER;
      hash = (53 * hash) + eyeColor_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static 4Enum.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 4Enum.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 4Enum.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 4Enum.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 4Enum.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 4Enum.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 4Enum.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 4Enum.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static 4Enum.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static 4Enum.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static 4Enum.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 4Enum.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(4Enum.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Person is used to identify users
     * across our systems 
     * </pre>
     *
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        4Enum.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return 4Enum.internal_static_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return 4Enum.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                4Enum.Person.class, 4Enum.Person.Builder.class);
      }

      // Construct using 4Enum.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        age_ = 0;

        firstName_ = "";

        lastName_ = "";

        smallPicture_ = com.google.protobuf.ByteString.EMPTY;

        isProfileVerified_ = false;

        height_ = 0F;

        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        eyeColor_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return 4Enum.internal_static_Person_descriptor;
      }

      @java.lang.Override
      public 4Enum.Person getDefaultInstanceForType() {
        return 4Enum.Person.getDefaultInstance();
      }

      @java.lang.Override
      public 4Enum.Person build() {
        4Enum.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public 4Enum.Person buildPartial() {
        4Enum.Person result = new 4Enum.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.age_ = age_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.smallPicture_ = smallPicture_;
        result.isProfileVerified_ = isProfileVerified_;
        result.height_ = height_;
        if (((bitField0_ & 0x00000040) != 0)) {
          phones_ = phones_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.phones_ = phones_;
        result.eyeColor_ = eyeColor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof 4Enum.Person) {
          return mergeFrom((4Enum.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(4Enum.Person other) {
        if (other == 4Enum.Person.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.getSmallPicture() != com.google.protobuf.ByteString.EMPTY) {
          setSmallPicture(other.getSmallPicture());
        }
        if (other.getIsProfileVerified() != false) {
          setIsProfileVerified(other.getIsProfileVerified());
        }
        if (other.getHeight() != 0F) {
          setHeight(other.getHeight());
        }
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
        if (other.eyeColor_ != 0) {
          setEyeColorValue(other.getEyeColorValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        4Enum.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (4Enum.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int age_ ;
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the last name as documented in the signup form
       * </pre>
       *
       * <code>string last_name = 3;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString smallPicture_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * small_picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       */
      public com.google.protobuf.ByteString getSmallPicture() {
        return smallPicture_;
      }
      /**
       * <pre>
       * small_picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       */
      public Builder setSmallPicture(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        smallPicture_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * small_picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       */
      public Builder clearSmallPicture() {
        
        smallPicture_ = getDefaultInstance().getSmallPicture();
        onChanged();
        return this;
      }

      private boolean isProfileVerified_ ;
      /**
       * <code>bool is_profile_verified = 5;</code>
       */
      public boolean getIsProfileVerified() {
        return isProfileVerified_;
      }
      /**
       * <code>bool is_profile_verified = 5;</code>
       */
      public Builder setIsProfileVerified(boolean value) {
        
        isProfileVerified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_profile_verified = 5;</code>
       */
      public Builder clearIsProfileVerified() {
        
        isProfileVerified_ = false;
        onChanged();
        return this;
      }

      private float height_ ;
      /**
       * <pre>
       * height of the person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       */
      public float getHeight() {
        return height_;
      }
      /**
       * <pre>
       * height of the person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       */
      public Builder setHeight(float value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * height of the person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          phones_ = new com.google.protobuf.LazyStringArrayList(phones_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPhonesList() {
        return phones_.getUnmodifiableView();
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public int getPhonesCount() {
        return phones_.size();
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public java.lang.String getPhones(int index) {
        return phones_.get(index);
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPhonesBytes(int index) {
        return phones_.getByteString(index);
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder setPhones(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder addPhones(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder clearPhones() {
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers tha is optional to provide in signup
       * </pre>
       *
       * <code>repeated string phones = 7;</code>
       */
      public Builder addPhonesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }

      private int eyeColor_ = 0;
      /**
       * <code>.Person.EyeColor eyeColor = 8;</code>
       */
      public int getEyeColorValue() {
        return eyeColor_;
      }
      /**
       * <code>.Person.EyeColor eyeColor = 8;</code>
       */
      public Builder setEyeColorValue(int value) {
        eyeColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Person.EyeColor eyeColor = 8;</code>
       */
      public 4Enum.Person.EyeColor getEyeColor() {
        @SuppressWarnings("deprecation")
        4Enum.Person.EyeColor result = 4Enum.Person.EyeColor.valueOf(eyeColor_);
        return result == null ? 4Enum.Person.EyeColor.UNRECOGNIZED : result;
      }
      /**
       * <code>.Person.EyeColor eyeColor = 8;</code>
       */
      public Builder setEyeColor(4Enum.Person.EyeColor value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eyeColor_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Person.EyeColor eyeColor = 8;</code>
       */
      public Builder clearEyeColor() {
        
        eyeColor_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final 4Enum.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new 4Enum.Person();
    }

    public static 4Enum.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public 4Enum.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0144-enum.proto\"\362\001\n\006Person\022\013\n\003age\030\001 \001(\005\022\022" +
      "\n\nfirst_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022\025\n" +
      "\rsmall_picture\030\004 \001(\014\022\033\n\023is_profile_verif" +
      "ied\030\005 \001(\010\022\016\n\006height\030\006 \001(\002\022\016\n\006phones\030\007 \003(" +
      "\t\022\"\n\010eyeColor\030\010 \001(\0162\020.Person.EyeColor\"<\n" +
      "\010EyeColor\022\020\n\014UNKKOW_COLOR\020\000\022\010\n\004BLUE\020\001\022\t\n" +
      "\005BROWN\020\002\022\t\n\005GREEN\020\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Age", "FirstName", "LastName", "SmallPicture", "IsProfileVerified", "Height", "Phones", "EyeColor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
