// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum_example/enum_example.proto

package enumpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DayOfTheWeek int32

const (
	DayOfTheWeek_UNKNOWNDAY DayOfTheWeek = 0
	DayOfTheWeek_SUNDAY     DayOfTheWeek = 1
	DayOfTheWeek_MONDAY     DayOfTheWeek = 2
	DayOfTheWeek_TUESDAY    DayOfTheWeek = 3
	DayOfTheWeek_WEDNESDAY  DayOfTheWeek = 4
	DayOfTheWeek_THURSDAY   DayOfTheWeek = 5
	DayOfTheWeek_FRIDAY     DayOfTheWeek = 6
	DayOfTheWeek_SATURDAY   DayOfTheWeek = 7
)

var DayOfTheWeek_name = map[int32]string{
	0: "UNKNOWNDAY",
	1: "SUNDAY",
	2: "MONDAY",
	3: "TUESDAY",
	4: "WEDNESDAY",
	5: "THURSDAY",
	6: "FRIDAY",
	7: "SATURDAY",
}

var DayOfTheWeek_value = map[string]int32{
	"UNKNOWNDAY": 0,
	"SUNDAY":     1,
	"MONDAY":     2,
	"TUESDAY":    3,
	"WEDNESDAY":  4,
	"THURSDAY":   5,
	"FRIDAY":     6,
	"SATURDAY":   7,
}

func (x DayOfTheWeek) String() string {
	return proto.EnumName(DayOfTheWeek_name, int32(x))
}

func (DayOfTheWeek) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8293647c26efc6c4, []int{0}
}

type EnumMessage struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DayOfTheWeek         DayOfTheWeek `protobuf:"varint,2,opt,name=day_of_the_week,json=dayOfTheWeek,proto3,enum=example.enumeration.DayOfTheWeek" json:"day_of_the_week,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnumMessage) Reset()         { *m = EnumMessage{} }
func (m *EnumMessage) String() string { return proto.CompactTextString(m) }
func (*EnumMessage) ProtoMessage()    {}
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8293647c26efc6c4, []int{0}
}

func (m *EnumMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumMessage.Unmarshal(m, b)
}
func (m *EnumMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumMessage.Marshal(b, m, deterministic)
}
func (m *EnumMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumMessage.Merge(m, src)
}
func (m *EnumMessage) XXX_Size() int {
	return xxx_messageInfo_EnumMessage.Size(m)
}
func (m *EnumMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EnumMessage proto.InternalMessageInfo

func (m *EnumMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EnumMessage) GetDayOfTheWeek() DayOfTheWeek {
	if m != nil {
		return m.DayOfTheWeek
	}
	return DayOfTheWeek_UNKNOWNDAY
}

func init() {
	proto.RegisterEnum("example.enumeration.DayOfTheWeek", DayOfTheWeek_name, DayOfTheWeek_value)
	proto.RegisterType((*EnumMessage)(nil), "example.enumeration.EnumMessage")
}

func init() { proto.RegisterFile("enum_example/enum_example.proto", fileDescriptor_8293647c26efc6c4) }

var fileDescriptor_8293647c26efc6c4 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0xcd, 0x2b, 0xcd,
	0x8d, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x47, 0xe6, 0xe8, 0x15, 0x14, 0xe5, 0x97,
	0xe4, 0x0b, 0x09, 0xc3, 0xb8, 0x20, 0xb9, 0xd4, 0xa2, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0xa5, 0x74,
	0x2e, 0x6e, 0xd7, 0xbc, 0xd2, 0x5c, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x3e, 0x2e,
	0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x0f, 0x2e,
	0xfe, 0x94, 0xc4, 0xca, 0xf8, 0xfc, 0xb4, 0xf8, 0x92, 0x8c, 0xd4, 0xf8, 0xf2, 0xd4, 0xd4, 0x6c,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x45, 0x3d, 0x2c, 0xa6, 0xe9, 0xb9, 0x24, 0x56, 0xfa,
	0xa7, 0x85, 0x64, 0xa4, 0x86, 0xa7, 0xa6, 0x66, 0x07, 0xf1, 0xa4, 0x20, 0xf1, 0xb4, 0xaa, 0xb8,
	0x78, 0x90, 0x65, 0x85, 0xf8, 0xb8, 0xb8, 0x42, 0xfd, 0xbc, 0xfd, 0xfc, 0xc3, 0xfd, 0x5c, 0x1c,
	0x23, 0x05, 0x18, 0x84, 0xb8, 0xb8, 0xd8, 0x82, 0x43, 0xc1, 0x6c, 0x46, 0x10, 0xdb, 0xd7, 0x1f,
	0xcc, 0x66, 0x12, 0xe2, 0xe6, 0x62, 0x0f, 0x09, 0x75, 0x0d, 0x06, 0x71, 0x98, 0x85, 0x78, 0xb9,
	0x38, 0xc3, 0x5d, 0x5d, 0xfc, 0x20, 0x5c, 0x16, 0x21, 0x1e, 0x2e, 0x8e, 0x10, 0x8f, 0xd0, 0x20,
	0x30, 0x8f, 0x15, 0xa4, 0xcb, 0x2d, 0xc8, 0x13, 0xc4, 0x66, 0x03, 0xc9, 0x04, 0x3b, 0x86, 0x84,
	0x06, 0x81, 0x78, 0xec, 0x4e, 0x1c, 0x51, 0x6c, 0x20, 0x57, 0x16, 0x24, 0x25, 0xb1, 0x81, 0x83,
	0xc2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x6c, 0xf3, 0x00, 0x2d, 0x01, 0x00, 0x00,
}
